### ISSUE TITLE
Add two new text fields

### ISSUE THREAD

**Issue by felskia** [map-egypt/admin#104]
Add new date field for Contract Signed

Add a text field at the end for 'Recommendations based on project experience'

**Comment by felskia** [comment]
Could you add this too? @kamicut if not I can ask Dylan maybe

**Comment by felskia** [comment]
@nbumbarger let me know if you can do this one as well. Both fields should not be required. We'll also need to surface these on the front-end.

**Comment by nbumbarger** [comment]
@felskia Can you try to get translations for these two fields? Unlike the front end, there won't be an easy way for them to add translations themselves.
