### ISSUE TITLE
Allow user to add a new project location without entering all the information

### ISSUE THREAD

**Issue by drewbo** [map-egypt/admin#105]
Users should be able to add a new:
- district within the same governorate
- lat/lng within the same district

cc: @felskia @DylanMoriarty

**Comment by felskia** [comment]
Here is the mockup 

<img width="769" alt="screen shot 2017-03-27 at 10 18 50 am" src="https://cloud.githubusercontent.com/assets/5421566/24361469/02ee633c-12d8-11e7-8fd6-997bfeae5b3e.png">

**Comment by kamicut** [comment]
When you click on 'Add a district' you get a prefilled governorate and new empty dropdowns for District and Lat/Lon

When you click on "Add another lat/long" you get prefilled governorate and District and new empty dropdowns Lat/Lon
