### ISSUE TITLE
Last form field for location 

### ISSUE THREAD

**Issue by felskia** [map-egypt/admin#111]
Name for lat, long point. Can we have a blank text field at the end that's label is "Village Name"? 

On the front-end we would just show that name to replace the other location that it's set to.

@kamicut let me know if you can help here or if it's hard at all.

**Comment by sethvincent** [comment]
Progress so far:

<img width="810" alt="screen shot 2017-04-26 at 5 55 01 pm" src="https://cloud.githubusercontent.com/assets/164214/25458828/881369f2-2aa9-11e7-9b63-83e11563cb60.png">

**Comment by sethvincent** [comment]
Closed by #118 and #116
