### ISSUE TITLE
Saving/Publishing Issue

### ISSUE THREAD

**Issue by felskia** [map-egypt/admin#113]
From Hagar:

"I am trying to edit project data now ( particularly the Egypt Food Security and...project) but for some reason every time I click submit in publishable format it doesn’t load the page or save it just stays as is. In draft mode it is saves fine. Seems that it could want me to add in other fields, but I am not getting any errors either.. It might be related to the project components (the fact that there is no Arabic translation) but not sure– see attached picture."

I tried to change a word, put it into publishable format and the same thing happened to me.

**Comment by sethvincent** [comment]
It seems like this happens when there's a form validation error and it isn't clear after clicking submit what's happening.

The individual fields that have validation errors show the error messages inline.

It could be useful to put an error message near the submit button that tells people to scroll up and fix the errors. It could be a generic "there's errors to fix" type message, or list all the errors.

**Comment by felskia** [comment]
@sethvincent I believe it used to scroll up to the top where the errors were. Do you see the errors though at all?

**Comment by sethvincent** [comment]
It doesn't scroll up, but it shows errors next to the relevant fields like this:

<img width="810" alt="screen shot 2017-04-27 at 1 32 18 pm" src="https://cloud.githubusercontent.com/assets/164214/25496211/11273864-2b4e-11e7-9ee3-1b410c307bc2.png">

The errors are in the bottom left.

**Comment by sethvincent** [comment]
We could add something like this that pops up on submit when an there are validation errors:
<img width="824" alt="screen shot 2017-04-27 at 1 55 17 pm" src="https://cloud.githubusercontent.com/assets/164214/25497048/40838c72-2b51-11e7-85e0-284199e4de71.png">

**Comment by felskia** [comment]
@sethvincent Yeah, that works. Just feel like we used to have that same thing at the top. Is it not there anymore? I'm happy with either.

**Comment by sethvincent** [comment]
Yeah, it's not at the top any more. Not sure why that is.

I'm almost done implementing what's in the above screenshot, so can make a pull request for it.

**Comment by sethvincent** [comment]
I found why it wasn't showing at the top and opened a pr with a fix: #116

**Comment by felskia** [comment]
@sethvincent I tried entering in some information and submitted it without a problem but now the place I submitted something... I can't delete it now. 

It's under: Egypt Food Security and Agribusiness Support and Project delays

**Comment by felskia** [comment]
@sethvincent Looking much better. The problem now is that long and lat shouldn't be required. I'm guessing that's why I'm getting the error because none of the fields are filled out.

**Comment by sethvincent** [comment]
@felskia i haven't seen errors for the lat/long fields after the latest commit to pr #116. what do the errors say?

**Comment by felskia** [comment]
@sethvincent I did a pull on 'form-errors' and I went to Egypt Food Security and Agribusiness Support and put it on publish and got the following errors: 

<img width="860" alt="screen shot 2017-05-01 at 11 03 46 am" src="https://cloud.githubusercontent.com/assets/5421566/25582989/e3364964-2e5d-11e7-9f51-71e57d90e4e8.png">


Which is why I'm guessing they're set up to be required since all lat long boxes for this project are blank.

**Comment by sethvincent** [comment]
This was fixed by #116.
