### ISSUE TITLE
Remove `undefined` from KMI component name

### ISSUE THREAD

**Issue by dereklieu** [map-egypt/admin#35]
![screen shot 2016-11-28 at 12 53 58 pm](https://cloud.githubusercontent.com/assets/1590802/20679641/cf11ca20-b569-11e6-86a4-62c242482c0a.png)

In the `kmi` field of the `project/:id` endpoint, the `component` property is the name of the thing followed by `- undefined`. See above. Can we do some better validation in the admin so we don't end up concat'ing `undefined` here? Or else do we need to remove whatever field is causing it, if it's not going to be used?

cc @kamicut @felskia

**Comment by kamicut** [comment]
@dereklieu this happens when the arabic field isn't added to the component name. The format is always "english - arabic". I can do the validation to not add the arabic name, but it should be required to properly display it if we had complete project data. What do you think is the right option here?

**Comment by dereklieu** [comment]
@kamicut I think we want this to be two separate fields in that case, not combined into a single string. That way we can switch when we're on the arabic page.

**Comment by kamicut** [comment]
I think that would complicate the admin form. The KMI component dropdown menu is linked to another part of the form (the components array) where the user adds the name of the component in english and arabic. The reason the dropdown combines both language strings is to reduce user error. cf @felskia 

Two approaches come to mind:
- Keep the display text the same but save the english version (or an id-fied version of the english text) to the API. 
- Parse the text on the frontend

**Comment by felskia** [comment]
@kamicut I mean, it's just in that format in that one section in the backend. Can't we just keep the format that they enter it in and show that on the API?
