### ISSUE TITLE
Actual Started Date - Projects

### ISSUE THREAD

**Issue by felskia** [map-egypt/admin#42]
Some projects only have year information. When you enter just a year for an actual start date and move on to the fields below the system scrubs the year from actual start date.

**Comment by kamicut** [comment]
I think the easiest way to implement this is to add an "N/A" option to the month field. What do you think @felskia ?

**Comment by felskia** [comment]
@kamicut I'd imagine if people don't have a month, they might not even click on the dropdown to select it.
