### ISSUE TITLE
Required Fields

### ISSUE THREAD

**Issue by felskia** [map-egypt/admin#52]
Note from Hagar: 

The required fields should be EVERYTHING EXCEPT:

- Project Amendments
- Corrective action (this needs to be added under project link)
- Local Project Manager
-Long/Lat
- Report Link
- Project Link
- Disbursement

**Comment by kamicut** [comment]
@felskia since Local Project Manager generates pages on the frontend, should it be required?

**Comment by felskia** [comment]
Nope, they don't seem to have this information very much if at all so we can't require.
