### ISSUE TITLE
Add additional field

### ISSUE THREAD

**Issue by felskia** [map-egypt/admin#75]
Please add an additional field called "Implementing partners"

**Comment by kamicut** [comment]
@felskia is this an array of strings or a textarea?

**Comment by felskia** [comment]
Hmmm... Good call. I'll ask Hagar.

**Comment by kamicut** [comment]
@felskia if it's a textarea, we should also ask if it's bilingual.

**Comment by felskia** [comment]
@kamicut this should be an input field
