### ISSUE TITLE
Project Locations - API

### ISSUE THREAD

**Issue by felskia** [map-egypt/admin#83]
Right now the when you have a Governorate and District, the data isn't being matched up on the front-end. It comes out as all of the Govenorates and then all of the Districts. E.g. Cairo, Cairo, Garden District, Pyramids. 

Where it should be: 
Garden District, Cairo
Pyramids, Cairo

**Comment by kamicut** [comment]
@felskia which project is this, I could look in the database if this is saved incorrectly.

**Comment by felskia** [comment]
@kamicut it's not entered incorrectly, I checked. I notice it most on: Promotion of Rural Incomes through Market Enhancement. But it's on others too. It's basically on any project that has projects with two of the same districts. (or at least is noticeable on those)

**Comment by kamicut** [comment]
@felskia oh, yeah I'm not saying they're entered incorrectly, I was looking at the data representation inside the database. It looks fine to me, so could this be a rendering issue on the front-end?
