### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by felskia** [map-egypt/admin#86]
@kamicut I think you may have already closed this ticket so am writing another. Issues are:

There are fields that **shouldn't be required** because they don't happen all the time. These are: 
       - All Arabic labels should not be required
       - Project Amendments
       - Project delays
       - Implementing Partners
       - Disbursed funds because we don't always have this information

Ones that should be required: 
       - Project Status
       - PLANNED START DATE
       - ACTUAL START DATE 

This is all I have for right now

Thanks!

**Comment by kamicut** [comment]
@felskia what about the other fields? Should the default be required or not required?

**Comment by felskia** [comment]
Give me an example about what other fields :)

**Comment by kamicut** [comment]
Here are the fields that are left: 
- Actual end date
- Planned end date
- Budget
- Sub-sector
- Description 
- KMI
- Location
- Number of beneficiaries
- Responsible Ministry
- SDS Indicator
- SDG Indicator

Based on #52 I have them set as required by default. But maybe we should double check?

**Comment by felskia** [comment]
@kamicut I would say that: 

- Actual end date - not required because sometimes the projects aren't finished
- Planned end date - should be required
- Budget  - we need to require currency, amount and exchange rate, and donor name. (if we don't have this we have nothing) :)
- Sub-sector - yes, required
- Description - KMI description?? If so then no it shouldn't be required
- KMI - in the KMI section. I think just having KPI, component, target, status is enough.
- Location - yes, required
- Number of beneficiaries - yes, required
- Responsible Ministry - not required since some of the data doesn't have this. 
- SDS Indicator - there is a required marker on these, I would say their required.
- SDG Indicator - there is a required marker on these, I would say their required.

I can ask but I'm pretty confident after having looked at the data.

**Comment by felskia** [comment]
Project Name - required
Objective - required
Visibility - required
Project Amendments - not required
Project Delays - not required
Corrective Action - not required
Project Status - required
Planned start date - should be required
Planned end date - should be required
Actual start date - not required
Actual end date - not required
Local Project Manager - not required
Responsible Ministry - not required
Implementing Partners - not required
Project Link - not required
Number of beneficiaries - required
SDS Indicator - required
SDG Indicator - required
Sub-sector - yes, required
Location - yes, required
Budget - we need to require currency, amount and exchange rate, and donor name. (if we don't have this we have nothing) :)
Description - KMI description?? If so then no it shouldn't be required
KMI - in the KMI section. I think just having KPI, component, target, status is enough.
Report Link - not required
